// 'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Navigation } from "@/src/components";
import NewNavigation from "@/src/components/new_navigation";
// import { useEffect } from 'react';
import { logCustomEvent } from "@/src/utils/firebase"; 

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Josh Arnow's Website",
  description: "Welcome to my website!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(() => {
  //   logCustomEvent('page_view', {
  //     page_title: "/",
  //     page_path: "/",
  //   });
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NewNavigation />
        {children}
      </body>
    </html>
  );
}
