import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Navigation } from "@/src/components";
import OldNavigation from "@/src/components/old_navigation";
import Navigation from "@/src/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: "Josh Arnow's Website",
  description: "Welcome to my website!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {/* <OldNavigation /> */}
        {children}
      </body>
    </html>
  );
}
