name: Validate codebase

on:
  push: # Runs on pushes targeting the default branch
    branches: ["master"]
  pull_request: # Runs on pull requests to the default branch
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run quality checks
        run: npm run check
